### ISSUE TITLE
"Error: must provide pattern" when running gulp command after bower update.

### ISSUE THREAD

**Issue by mikejoseph23** [sagiegurari/angular-web-notification#20] opened 2016-11-05 19:48 UTC
#### Problem Description

I discovered this problem this morning when I did a 'bower update' command and my dependencies got updated. After doing this, my 'gulp build' command that I created stopped working. I was able to trace the problem down to this dependency. If I perform, the command 'bower uninstall angular-web-notification --save' then my gulp script would run successfully. But after reinstalling it by using the following command, 'bower install angular-web-notification' the error returned. 

Below a command line session, which proves the error exists. To summarize:
1. Ran my gulp command and it finished successfully.
2. Installed the angular-web-notification bower package.
3. Re-ran my gulp command again and I got the error.
4. Uninstalled the angular-web-notification.
5. Re-ran my gulp command and it finished successfully.

#### Code Example

C:\git\Timer>gulp
[15:41:33] Using gulpfile C:\git\Timer\gulpfile.js
[15:41:33] Starting 'help'...

Main Tasks
------------------------------
    browserSyncReload
    build
    bump
    clean
    copyfiles
    default
    fonts
    help
    images
    inject
    optimize
    styles
    templatecache
    test
    vet
    wiredep

Sub Tasks
------------------------------
    build-deploy
    build-specs
    clean-code
    clean-deploy
    clean-fonts
    clean-images
    clean-styles
    compress-windows-app
    less-watcher
    pre-commit
    serve-build
    serve-dev
    serve-specs

[15:41:34] Finished 'help' after 97 ms
[15:41:34] Starting 'default'...
[15:41:34] Finished 'default' after 26 μs

C:\git\Timer>bower install angular-web-notification --save
bower angular-web-notification#*           cached https://github.com/sagiegurari/angular-web-notification.git#1.0.16
bower angular-web-notification#*         validate 1.0.16 against https://github.com/sagiegurari/angular-web-notification.git#*
bower html5-desktop-notifications#~3       cached https://github.com/ttsvetko/HTML5-Desktop-Notifications.git#3.0.0
bower html5-desktop-notifications#~3     validate 3.0.0 against https://github.com/ttsvetko/HTML5-Desktop-Notifications.git#~3
bower angular-web-notification#^1.0.16    install angular-web-notification#1.0.16
bower html5-desktop-notifications#~3      install html5-desktop-notifications#3.0.0

angular-web-notification#1.0.16 src\Timer.Angular\bower_components\angular-web-notification
├── angular#1.5.5
└── html5-desktop-notifications#3.0.0

html5-desktop-notifications#3.0.0 src\Timer.Angular\bower_components\html5-desktop-notifications

C:\git\Timer>gulp
C:\git\Timer\node_modules\glob\sync.js:29
    throw new Error('must provide pattern')
    ^

Error: must provide pattern
    at new GlobSync (C:\git\Timer\node_modules\glob\sync.js:29:11)
    at Function.globSync [as sync] (C:\git\Timer\node_modules\glob\sync.js:24:10)
    at C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:109:14
    at Array.reduce (native)
    at findMainFiles (C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:107:31)
    at C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:161:17
    at forOwn (C:\git\Timer\node_modules\wiredep\node_modules\lodash\dist\lodash.js:2106:15)
    at Function.forEach (C:\git\Timer\node_modules\wiredep\node_modules\lodash\dist\lodash.js:3303:9)
    at C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:181:11
    at forOwn (C:\git\Timer\node_modules\wiredep\node_modules\lodash\dist\lodash.js:2106:15)

C:\git\Timer>bower uninstall angular-web-notification --save
bower uninstall     angular-web-notification
bower uninstall     html5-desktop-notifications

C:\git\Timer>gulp
[15:42:11] Using gulpfile C:\git\Timer\gulpfile.js
[15:42:11] Starting 'help'...

Main Tasks
------------------------------
    browserSyncReload
    build
    bump
    clean
    copyfiles
    default
    fonts
    help
    images
    inject
    optimize
    styles
    templatecache
    test
    vet
    wiredep

Sub Tasks
------------------------------
    build-deploy
    build-specs
    clean-code
    clean-deploy
    clean-fonts
    clean-images
    clean-styles
    compress-windows-app
    less-watcher
    pre-commit
    serve-build
    serve-dev
    serve-specs

[15:42:11] Finished 'help' after 130 ms
[15:42:11] Starting 'default'...
[15:42:11] Finished 'default' after 24 μs

C:\git\Timer>

#### Error Stack/Info (if any)

Error: must provide pattern
    at new GlobSync (C:\git\Timer\node_modules\glob\sync.js:29:11)
    at Function.globSync [as sync] (C:\git\Timer\node_modules\glob\sync.js:24:10)
    at C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:109:14
    at Array.reduce (native)
    at findMainFiles (C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:107:31)
    at C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:161:17
    at forOwn (C:\git\Timer\node_modules\wiredep\node_modules\lodash\dist\lodash.js:2106:15)
    at Function.forEach (C:\git\Timer\node_modules\wiredep\node_modules\lodash\dist\lodash.js:3303:9)
    at C:\git\Timer\node_modules\wiredep\lib\detect-dependencies.js:181:11
    at forOwn (C:\git\Timer\node_modules\wiredep\node_modules\lodash\dist\lodash.js:2106:15)

**Comment by sagiegurari** [comment] 2016-11-06 04:52
The issue is that I updated the html5 notification dependency from my fork to the original repo since the owner did many changes that removed the need for my fork.
So now angular-web-notification depends on: html5-desktop-notifications instead of HTML5-Desktop-Notifications2
My guess you need to update your gulpfile.js and includes in your html (or some js you use to include all your dependencies in so browserify will use).

The new html5 component should be at: src\Timer.Angular\bower_components\html5-desktop-notifications\dist\Notification.js

**Comment by mikejoseph23** [comment] 2016-11-06 05:06
Hmmm... My gulpfile script automatically includes all packages installed my bower_components directory as part of the script. I see that the file you reference does get installed as part of the bower installation, but the gulp script still fails. I'm not sure what I'm missing if the problem is on my end. The stack trace doesn't tell me anything aside from the node_modules scripts.

**Comment by sagiegurari** [comment] 2016-11-06 05:13
Just tested with browserify and it works well so it is not that. Not sure what is in your gulp but the module supports browserify.
Can you please check your includes that they are up to date with the new dependency?

**Comment by mikejoseph23** [comment] 2016-11-06 05:21
I'm a little new to gulp. I'm using john papa's gulp patterns as a starting point for what I'm doing. 
https://github.com/johnpapa/gulp-patterns

Should I be checking the bower.json file to look for the right version numbers and the new notification dependency?

**Comment by sagiegurari** [comment] 2016-11-06 05:51
I'm not familiar with that repo at all, so can't tell what it is doing.
you are not setting what dependencies you are using at all anywhere?
If so I guess it is an issue with html5 notification repo because it doesn't set the 'main' in its bower.json which means you might need to point to the right file somewhere in your gulp or some other html file in your repo instead.

**Comment by mikejoseph23** [comment] 2016-11-06 22:36
Fair enough. I will close the issue. If anyone else experiences issues, I think they can re-open it. Thanks.

**Comment by linkthrow** [comment] 2016-11-22 17:09
Having the same issue

![screen shot 2016-11-22 at 17 08 51](https://cloud.githubusercontent.com/assets/16664738/20533702/64375e5a-b0d6-11e6-9ad8-32a6a8e63358.png)

**Comment by sagiegurari** [comment] 2016-11-22 17:15
My hunch is that the issue is with the html5 desktop notification sub dependency.
As a test, can you remove the dependecy from my repo and add to the html5 dependency? If error persists then it is there.
When i reviewed it's bower.json it was missing things like main js file.
So please run that test and reply with the results

**Comment by linkthrow** [comment] 2016-11-22 17:15
as a temp fix, I have hard coded my bower release to be at: 1.0.14 and it works

**Comment by sagiegurari** [comment] 2016-11-22 18:39
Ya but that is a version that is using an old html 5 desktop notification sub dependency.
Going forward you will run into an issue so if you can do this simple test or provide me of a test case to try it out myself so I'll be able to contact the author of that repo to tell him what he needs to fix.

**Comment by Rid** [comment] 2016-11-23 14:14
Having the same issue, we've hard coded the release at 1.0.15 as a temp fix. When removing your repo and replacing with:

`"html5-desktop-notifications": "~3"`

It errors out with the same issue, the bower.json seems to be broken. I have made an issue here:

https://github.com/ttsvetko/HTML5-Desktop-Notifications/issues/44

Please feel free to contribute.

**Comment by sagiegurari** [comment] 2016-11-23 14:30
Thanks a lot 👍 
I had a feeling that their bower.json is the issue, so thanks for confirming.
I'll make sure to keep this issue open to followup on that one.

**Comment by sagiegurari** [comment] 2016-11-23 19:28
To enable people to continue working, I'll probably fork the html 5 desktop notification dependency and fix the bower.json there.
Hopefully it should resolve your issue until the owner of the main repo fixes things.
Hopefully will do it tomorrow.

**Comment by Rid** [comment] 2016-11-23 19:38
Thanks @sagiegurari really appreciate the effort

**Comment by keithgallant** [comment] 2016-11-23 21:30
@sagiegurari I am getting this same error when I try to start up my project using grunt serve. From the sounds of your solution it should correct my issue. So I would change the "html5-desktop-notifications": "~3", in the dependancies to something older?

**Comment by sagiegurari** [comment] 2016-11-23 21:34
no, i'm going to fork that dependency and fix his bower.json which should resolve the issue.
if you want to manually fix right now your issue locally, you should change the bower.json in the html5-desktop-notifications folder to point to the dist/Notification.js file

**Comment by sagiegurari** [comment] 2016-11-23 21:42
i'm going to release a new in the next few minutes, which I would hope you guys could validate that it solves the issue.
Will keep you posted.

**Comment by sagiegurari** [comment] 2016-11-23 21:57
New version pushed, please run

````sh
bower uninstall angular-web-notification && bower install
````

to get latest version.
Also keep in mind that the new version will create a folder html5-desktop-notifications2 instead of html5-desktop-notifications so if you have imports anywhere (html/gulp/...) make sure to fix them.

**Comment by sagiegurari** [comment] 2016-11-23 21:58
I would like to get some feedback if any of you could please test it so I'll know if anything else needs fixing regarding this issue.

**Comment by mvarshavsky** [comment] 2016-11-23 21:59
Cleared it up for me

**Comment by sagiegurari** [comment] 2016-11-23 22:02
@mvarshavsky thanks a lot 👍 
So I'll be keeping this new fork until original repo is fixed via ttsvetko/HTML5-Desktop-Notifications#44

**Comment by Rid** [comment] 2016-11-23 22:03
@sagiegurari thanks, working now 👍

**Comment by MladenStanojevic** [comment] 2016-11-24 17:01
That works for me as well

**Comment by sagiegurari** [comment] 2016-11-24 17:08
Thanks all for confirming. I guess it is safe to close this issue for now

**Closed by sagiegurari** 2016-11-24 17:08 UTC
Labels: 3rd Party Issue
